.TH A2 Part B 1
.SH NAME
Scripting Requirement 2 \– basic information with post processing
.SH SYNOPSIS
.B ./b_req2.sh
[ \fIOPTION\fI ]
.SH DESCRIPTION
.B ./b_req2.sh
This requirement is to write a bash script using getopts to receive the arguments that
provides some ability
.SH OPTIONS
.TP
.BR \-a 
the number of cpu cores on the system
.TP
.BR \-b 
the current process’ priority (nice number)
.TP
.BR \-c 
the total number of processes running under the current user
.TP
.BR \-d 
the number of open file descriptors to regular files owned by the current user
.TP
.BR \-e 
the maximum system stack size.
