.TH A2 Part B 1
.SH NAME
Scripting Requirement 1 \– basic information
.SH SYNOPSIS
.B ./b_req1.sh 
[\fIARGUMENT\fI]
.SH DESCRIPTION
.B ./b_req1.sh
Based on the argument passed in will display one of the following:
- the amount of free and occupied memory on the system in human readable format
- the amount of disk space occupied and free on the system in human readable
format.
- the connection information for each network connection on the system including the ip and mac addresses for all connections on the system
- The system load average.
.SH OPTIONS
